### ISSUE TITLE
Use --token instead of --api-key

### ISSUE THREAD

**Issue by otisg** [sematext/logsene-cli#1]
--app-key should be --token, because that is the terminology Logsene uses.  Using --app-key name instead of --token is confusing, plus there is another very similar parameter (--api-key).

**Comment by otisg** [comment]
Hm, no, maybe --api-key really is the API key, @mbonaci ?

**Comment by mbonaci** [comment]
As specified in the README, `--api-key` is your account's key (which is retrieved as you log in and is used to get all applications so you can choose one to work with) and `--token` is a specific app's key (retrieved as you choose an app).
At the beginning, `--token` was named `--app-key`, but it was renamed a while back, following your suggestion :)
