### ISSUE TITLE
Issue when attempting to specify which fields to bring back using -f

### ISSUE THREAD

**Issue by patrickbray** [sematext/logsene-cli#7]
Hi, 

I am running into an issue when attempting to specify which fields to bring back using -f

```
root@956d26155944:~/.config/configstore/logsene# logsene search -q tags:httpd -f request
/usr/local/lib/node_modules/logsene-cli/commands/search.js:65
        opts.body.fields(f);
                  ^

TypeError: opts.body.fields is not a function
    at child._run [as run] (/usr/local/lib/node_modules/logsene-cli/commands/search.js:65:19)
    at /usr/local/lib/node_modules/logsene-cli/node_modules/ronin/lib/command.js:190:4
    at iterate (/usr/local/lib/node_modules/logsene-cli/node_modules/ronin/node_modules/async/lib/async.js:146:13)
    at Timeout._onTimeout (/usr/local/lib/node_modules/logsene-cli/node_modules/ronin/node_modules/async/lib/async.js:157:25)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)
```

**Comment by otisg** [comment]
Which version of Node are you running, @patrickbray ?

**Comment by patrickbray** [comment]
```
root@956d26155944:~/.config/configstore/logsene# node --version
v9.5.0
```

I am running in a docker container as I ran into some issues with the login as well. 

```
No active sessions. Please log in using your Sematext account:
Enter your username: patrick@redacted.com
Enter your password:
Successfuly logged in and retrieved API key.
: Could not parse the response body to get application listing.
Exiting
```

I believe the above error is because I need to switch users. I managed to get around this by manually entering the username & api-key into the json file in `~/.config/configstore/logsene`. 

Just tested on my host running: 

```
node --version
v8.9.1
```

and seems to have the same issue.

**Comment by mbonaci** [comment]
Hi @patrickbray,
thanks for reporting.
I'll take a look and ping you back.
Can you provide me with the `Dockerfile` that you're using. Thx

**Comment by mbonaci** [comment]
Hi @patrickbray,
we upgraded our ES recently, so the `fields` stopped working:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored",
        "line" : 1,
        "col" : 41
      }
    ],
    "type" : "parsing_exception",
    "reason" : "The field [fields] is no longer supported, please use [stored_fields] to retrieve stored fields or _source filtering if the field is not stored",
    "line" : 1,
    "col" : 41
  },
  "status" : 400
}
```
I fixed the issue and published the new version to npm.
Reinstall your logsene-cli and try again. Feel free to open another issue if you'll still have issues.

BTW FYI I noticed you're not using `-t` switch. That means you're searching only within last 60 minutes.

**Comment by patrickbray** [comment]
Thanks @mbonaci I can confirm that after the update the `-f` switch is now working for me. 

I am still having an issue with the login side of things though so might raise a separate issue for this. 

Given the session times out and removes the credentials from the json file in `~/.config/configstore/logsene` it isn't really workable to manually keep updating this.
